version: 2.1

jobs:
  job:
    parameters:
      foo:
        type: string
      bar:
        type: string
      bool_true:
        type: boolean
        default: true
      bool_false:
        type: boolean
        default: false
    docker:
      - image: circleci/node:latest
    steps:
      - run: |
          echo 1 <<parameters.foo>>
          echo 2 <<#parameters.foo>><<parameters.foo>><</parameters.foo>>
          echo 3 <<#parameters.bar>><<parameters.bar>><</parameters.bar>>

          echo 4 <<#parameters.bool_true>><<parameters.bool_true>><</parameters.bool_true>>
          echo 5 <<#parameters.bool_false>><<parameters.bool_false>><</parameters.bool_false>>

workflows:
  workflow:
    jobs:
      - job:
          foo: test
