description: # The purpose of this orb

orbs:
  yasuhiroki:
    executors:
      default:
        docker:
          - image: alpine:latest
    commands:
      install:
        steps:
          - run: |
              test -f /usr/local/bin/reviewdog \
                || \
              wget https://github.com/haya14busa/reviewdog/releases/download/0.9.11/reviewdog_linux_amd64 -O /usr/local/bin/reviewdog \
                && \
              chmod +x /usr/local/bin/reviewdog
          - run: ls -l /usr/local/bin/reviewdog
      reviewdog:
        steps:
          - run: ls -l /usr/local/bin/reviewdog
          - run: cat lint-result.txt | reviewdog -f=rubocop -reporter=github-pr-review
    jobs:
      reviewdog:
        executor: default
        steps:
          - install
          - reviewdog

version: 2.1
workflows:
  main:
    jobs:
      - yasuhiroki/reviewdog
