version: 2
jobs:
  build:
    machine: true
    working_directory: ~/app
    steps:
      - run:
        name: Setup docker
        command: |
          sudo rm -rf /usr/bin/docker
          curl -sSL https://get.docker.com/ | sh
          sudo usermod -aG docker `whoami`
          sudo sh -c 'curl -L https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose'
      - run: |
          docker-compose --version

