version: 2.1

executors:
  a:
    docker:
      - image: docker:17.05.0-ce-git

commands:
  a:
    steps:
      - run: echo

jobs:
  Name:
    executor: a
    steps: [ a ]
  yasuhiroki:
    executor: a
    steps: [ a ]
  Community:
    executor: a
    steps: [ a ]
  CircleCI_User_Community:
    executor: a
    steps: [ a ]
  Favorite:
    executor: a
    steps: [ a ]
  Vim:
    executor: a
    steps: [ a ]
  ShellScript:
    executor: a
    steps: [ a ]
  Automation:
    executor: a
    steps: [ a ]

  r1:
    executor: a
    steps: [ a ]
  r2:
    executor: a
    steps: [ a ]
  r3:
    executor: a
    steps: [ a ]

workflows:
  introduce:
    jobs:
      - Name
      - yasuhiroki:
          requires:
            - Name

      - Community
      - CircleCI_User_Community:
          name: CircleCI UC
          requires:
            - yasuhiroki
            - Community

      - Favorite
      - Vim:
          requires:
            - CircleCI_User_Community
            - Community
      - ShellScript:
          requires:
            - CircleCI_User_Community
            - Community
      - Automation:
          name: 自動化
          requires:
            - CircleCI_User_Community
            - Community
