version: 2

jobs:
  build1: &job
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run: uname
  build2:
    <<: *job
  build3:
    <<: *job
  build4:
    <<: *job
  build5:
    <<: *job


workflows:
  version: 2
  build:
    jobs:
      - build1
      - build2:
          requires:
            - build1
      - build3:
          requires:
            - build1
          filters:
            branches:
              only:
                - workflow
      - no_should_not_build3:
          requires:
            - build1
          filters:
            branches:
              only:
                - master
                - workflow
      - build4:
          requires:
            - build5
      - build5:
          requires:
            - build1

