version: 2.1

orbs:
  hub:
    commands:
      install:
        description:
          Install hub command
        steps:
          - run: |
              wget $(curl -s https://api.github.com/repos/github/hub/releases/latest | grep -o 'https://.*hub-linux-amd64.*tgz')
              tar zxf hub-linux-amd64-*.tgz
              if which sudo > /dev/null; then
                sudo ./hub-linux-amd64-2.13.0/install
              else
                ./hub-linux-amd64-2.13.0/install
              fi
              rm -rf hub-linux-amd64-2.13.0
      create-release:
        description:
          Create GitHub release by hub command
        parameters:
          draft:
            description: draft release
            type: boolean
            default: false
          prerelease:
            description: prerelease
            type: boolean
            default: false
          message:
            description: release title
            type: string
            default: ""
          message-file:
            description: release title and body
            type: string
            default: ""
          target:
            description: branch name to attach the release
            type: string
            default: ""
          tag:
            description: release tag name
            type: string
        steps:
          - run: |
              hub release create \
              <<#parameters.draft>>-d<</parameters.draft>> \
              <<#parameters.prerelease>>-p<</parameters.prerelease>> \
              <<#parameters.message>>-m <<parameters.message>><</parameters.message>> \
              <<#parameters.message-file>>-F <<parameters.message-file>><</parameters.message-file>> \
              <<#parameters.target>>-t <<parameters.target>><</parameters.target>> \
              <<parameters.tag>>

jobs:
  job_1:
    docker:
      - image: circleci/node:latest
    steps:
      - hub/install
      - hub/create-release:
          message: test
          target: master
          tag: test

workflows:
  workflow_1:
    jobs:
      - job_1
