version: 2.1

executors:
  a:
    docker:
      - image: docker:17.05.0-ce-git

commands:
  a:
    steps:
      - run: echo

jobs:
  Name:
    executor: a
    steps: [ a ]
  yasuhiroki:
    executor: a
    steps: [ a ]
  Community:
    executor: a
    steps: [ a ]
  CircleCI_User_Community:
    executor: a
    steps: [ a ]
  Favorite:
    executor: a
    steps: [ a ]
  Vim:
    executor: a
    steps: [ a ]
  ShellScript:
    executor: a
    steps: [ a ]
  Automation:
    executor: a
    steps: [ a ]

  r1:
    executor: a
    steps: [ a ]
  r2:
    executor: a
    steps: [ a ]
  r3:
    executor: a
    steps: [ a ]

workflows:
  introduce:
    jobs:
      - r1
      - Name:
          requires:
            - r1
      - yasuhiroki:
          requires:
            - Name

      - r2:
          requires:
            - r1
      - Community:
          requires:
            - r2
      - CircleCI_User_Community:
          requires:
            - Community

      - r3:
          requires:
            - r2
      - Favorite:
          requires:
            - r3
      - Vim:
          requires:
            - Favorite
      - ShellScript:
          requires:
            - Favorite
      - Automation:
          name: 自動化
          requires:
            - Favorite

