version: 2.1

executors:
  a:
    docker:
      - image: docker:17.05.0-ce-git

commands:
  a:
    steps:
      - run: echo

jobs:
  yasuhiroki:
    executor: a
    steps: [ a ]
  CircleCI_User_Community:
    executor: a
    steps: [ a ]
  Vim:
    executor: a
    steps: [ a ]
  ShellScript:
    executor: a
    steps: [ a ]
  Automation:
    executor: a
    steps: [ a ]

workflows:
  introduce:
    jobs:
      - yasuhiroki:
          name: "@yasuhiroki"

      - CircleCI_User_Community:
          name: CircleCI UC
          requires:
            - "@yasuhiroki"

      - Vim:
          requires:
            - CircleCI UC
      - ShellScript:
          requires:
            - CircleCI UC
      - Automation:
          name: 自動化
          requires:
            - CircleCI UC
