version: 2.1

executors:
  a:
    docker:
      - image: docker:17.05.0-ce-git

commands:
  a:
    steps:
      - run: echo

jobs:
  アカウント:
    executor: a
    steps: [ a ]
  yasuhiroki:
    executor: a
    steps: [ a ]

workflows:
  introduce:
    jobs:
      - アカウント
      - yasuhiroki:
          requires:
            - name

