version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.3
    steps:
      - checkout
      - run: echo build
  build2:
    docker:
      - image: circleci/ruby:2.3.3
    steps:
      - checkout
      - run: echo build2
  build3:
    docker:
      - image: circleci/ruby:2.3.3
    steps:
      - checkout
      - run: echo build2

workflows:
  version: 2
  test:
    jobs:
      - build
      - build2:
          requires:
            - build

