version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/actions/stale.git
            cd stale
            npm install ./toolkit/*
            npm run build
            env INPUT_REPO-TOKEN=${GITHUB_TOKEN} node lib/main.js
          environment:
            # INPUT_REPO-TOKEN: xxx
            INPUT_DAYS-BEFORE-STALE: 1
            INPUT_DAYS-BEFORE-CLOSE: 1
            INPUT_STALE-ISSUE-LABEL: stale
            INPUT_STALE-PR-LABEL: stale
            INPUT_STALE-ISSUE-MESSAGE: 'stale issue'
            INPUT_STALE-PR-MESSAGE: 'stale pull request'
            INPUT_OPERATIONS-PER-RUN: 30
            GITHUB_REPOSITORY: yasuhiroki/enjoy-circleci

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: yasuhiroki
