description: # The purpose of this orb

orbs:
  yasuhiroki:
    executors:
      reviewdog:
        docker:
          - image: alpine:latest
    commands:
      install:
        steps:
          - restore_cache:
              keys:
                - reviewdog-0.9.8
          - run: |
              test -f /usr/local/bin/reviewdog \
                || \
              wget https://github.com/haya14busa/reviewdog/releases/download/0.9.8/reviewdog_linux_amd64 -O /usr/local/bin/reviewdog \
                && \
              chmod +x /usr/local/bin/reviewdog
          - save_cache:
              key: reviewdog-0.9.8
              paths:
                - /usr/local/bin/reviewdog
      reviewdog:
        steps:
          - run: reviewdog --help
    jobs:
      reviewdog:
        executor: reviewdog
        steps:
          - install
          - reviewdog

version: 2.1
workflows:
  main:
    jobs:
      - yasuhiroki/reviewdog
